### ISSUE TITLE
Mac/linux 是不是直接跑这个脚本就可以了

### ISSUE THREAD

**Issue by chenshun00** [HaujetZhao/CapsWriter#1]
RT

**Comment by HaujetZhao** [comment]
安装依赖后，运行 run.py 就行了。会自动生成 token.ini，在里面填上 api，就能够进行识别了。

需要安装以下模块：

- keyboard
- pyaudio
- configparser
- aliyunsdkcore
- alibabacloud-nls-python-sdk

其中：

- pyaudio 在不是太好安装，在 linux 上需要先安装 portaudio-dev ，再用 pip 安装 pyaudio
- alibabacloud-nls-python-sdk 不是通过 python 安装，而是通过 [阿里云官方文档的方法](https://help.aliyun.com/document_detail/120693.html) 进行安装。
- 其他的使用pip安装就行

**Comment by chenshun00** [comment]
好，我试试
