### ISSUE TITLE
Help!!!  Unanticipated host error

### ISSUE THREAD

**Issue by 51883** [HaujetZhao/CapsWriter#2]
1//:按住 CapsLock 键 0.3 秒后开始说话... [Errno -9999] Unanticipated host error
Hi, I have a problem,  when I ready the token.ini, I got the error.
How can I fix this?

**Comment by HaujetZhao** [comment]
> 1//:按住 CapsLock 键 0.3 秒后开始说话... [Errno -9999] Unanticipated host error
> Hi, I have a problem, when I ready the token.ini, I got the error.
> How can I fix this?

弃更了。用我的 Quick Cut 吧，可视化界面，内置了这个功能。

**Comment by liyuyang** [comment]
大佬，借楼问一句，有没有离线的语音识别库啊？我想做个不用调api的工具

**Comment by HaujetZhao** [comment]
2.0 发布，有可视化界面了
