### ISSUE TITLE
InvalidAccessKeyID

### ISSUE THREAD

**Issue by MaxZH42** [HaujetZhao/CapsWriter#5]
已经尝试过多次，确保AccessKeyID和AccessKeySecret都是对的，但还是提示Specified access key is not found or invalid.已经确保云服务打开了权限。

**Comment by HaujetZhao** [comment]
重新开一个用户 accessKey，设置权限，再试试。如果不行，用户权限界面给我看下。

**Comment by MaxZH42** [comment]
> 重新开一个用户 accessKey，设置权限，再试试。如果不行，用户权限界面给我看下。

![QQ截图20201228125408](https://user-images.githubusercontent.com/26235806/103190438-df2f2500-48c8-11eb-9a75-1815edfa5a5e.png)

**Comment by HaujetZhao** [comment]
帮助页面进群，我给远程看看

**Comment by MaxZH42** [comment]
> 帮助页面进群，我给远程看看

我一个字一个字手动输入然后可以用了。。

**Comment by HaujetZhao** [comment]
那就是复制到空格或者换行符了。我昨天修复了，重新下载发行版本，再往里边复制api的时候，空格和换行符就都不会进去了。
