### ISSUE TITLE
醉了

### ISSUE THREAD

**Issue by goodwinfame** [HaujetZhao/CapsWriter#8]
刚开始一看简介，以为是一个语音识别项目，牛逼啊。
往下翻，发现原来是个壳子，还是调用的三方服务，原来如此。
再往下，4个大大的收钱二维码，醉了。。。
就这样还要赞助？？真的好意思吗？？

**Comment by nobodxbodon** [comment]
不给钱不能用么？
有类似功能但更“牛逼”的开源项目推荐一下？

**Comment by goodwinfame** [comment]
不该打击开源者积极性，关了。
