### ISSUE TITLE
能否增加一个fn，用于替换大写的按键？

### ISSUE THREAD

**Issue by asuplive** [HaujetZhao/CapsWriter#9]
大写按键的缺点有
1.单独按一下就有功能，轻按就直接切换了大小写，这个是很容易发生的
2.而且还很容易按到旁边的shift按钮

fn，按钮的优点有
1.单独按键没有功能
2.在最左下角可以盲按

**Comment by noteaplz** [comment]
支持，cap确实会造成一点问题，有时候语音输入说完，键盘输入法就被切换成大写的英文状态了，添加标点的时候就变成英文的标点了。

希望可以增加修改快捷键的功能。

**Comment by dennischancs** [comment]
兄弟们，知道作者为什么不回答你吗？因为**Fn键不能单独按的，只能与最上面一排功能键组合**，单手操作就很复杂了（见讯飞语音输入法的默认快捷键，Readme.md有说）。
问题可以close了，无解的。

**Comment by pluveto** [comment]
Fn 是不可能的，因为 Fn 是键盘驱动实现的。我建议是提供一个进程间通信方式，然后我们通过这个东西去控制。从而可以实现自定义快捷键等。
